# Generated by Django 3.1.3 on 2021-01-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Link'),
        ),
    ]
